version: "3.1"

services:
  scheduler:
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: daskdev/dask
    hostname: dask-worker1
    command: ["dask-worker", "tcp://scheduler:8786"]

  worker2:
    image: daskdev/dask
    hostname: dask-worker2
    command: ["dask-worker", "tcp://scheduler:8786"]

  jupyter:
    hostname: jupyter-dask
    build:
      eljupyter/.
    ports:
      - "8888:8888"




 import xarray as xr 

 import xarray as xr
 from dask.distributed import Client, progress
c = Client("scheduler:8786")
c